import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Providers from "./provider";
import SideBar from "@/src/components/SideBar";
import { LayoutGroup } from "framer-motion";


export const metadata = {
  title: "Media Search",
  description: "Generated by create next app.... for now",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`bg-[#F0F0DB]`}
      >
        <Providers>
          <div className="sm:flex w-screen">
            <div className="fixed sm:static z-999 bottom-0 left-0 right-0">
              <LayoutGroup>
                <SideBar />
              </LayoutGroup></div>
            <div className="max-h-screen overflow-auto flex-1 ">
              {children}
            </div>
          </div>
        </Providers>
      </body>
    </html>
  );
}
