import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Providers from "./provider";
import SideBar from "@/src/components/SideBar";
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Media Search",
  description: "Generated by create next app.... for now",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <Providers>
          <div className="flex w-screen">
            <div><SideBar/></div>
            <div className="max-h-screen overflow-auto flex-1">
              {children}
            </div>
          </div>
        </Providers>
      </body>
    </html>
  );
}
